[env:m5stack-nanoc6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-c6-devkitm-1
board_build.partitions = huge_app.csv
framework = arduino
lib_extra_dirs = ../../lib
upload_speed = 1500000
monitor_speed = 115200
build_flags =
    -I ../../include
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    -D CORE_DEBUG_LEVEL=5
lib_deps =
    m5stack/M5Unified@0.2.19
